import h2MovingAction from "./h2MovingAction";
import fadeUp from "./fadeUp";
import fromSideGimmick from "./fromSideGimmick";
import infoBg from "./infoBg";
import mySlick from "./mySlick";
mySlick();
fadeUp();
h2MovingAction();
fromSideGimmick();
infoBg();
